Issue2
shapurid/backend-project-lvl4 pull request #10
Opened 2020-10-08 14:38 UTC by shapurid

2020-10-11 16:04 UTC, foofaev requested changes

2020-10-11 16:04 UTC, foofaev commented on server/routes/users.js
> +          .filter(([key, value]) => (key !== '_method') && (value.length > 0))
lodash pickBy или omitBy

2020-10-11 16:04 UTC, foofaev commented on server/routes/users.js
> +        if (sessionId !== routeId) {
Замечаешь, что это приходится повторять из метода в метод?
Можно добавить декоратор и положить его в хуки метода

2020-10-12 21:39 UTC, shapurid commented on server/routes/session.js
> +          throw new SchemaError(validationError);
К сожалению, если использавать schemaErrorFormatter, то перестает работать fastify-method-override.

2020-10-13 20:09 UTC, foofaev commented on server/index.js
> +    const isProfile = /^\/users\/\d+/.test(req.url);
Получаетсяя, прямо тут ты зашиваешь путь
Потом, поменяешь путь - придется и тут менять?
Лучше в хуке только оставить выставление currentUser + isSignedIn

А я говорил про добавь или декоратор, или просто функцию. И вызывай ее на нужном методе в хуке preHandled

2020-10-13 20:10 UTC, merged

2020-10-14 09:25 UTC, shapurid commented on server/routes/users.js
> +        const routeId = parseInt(req.params.id);
Это лодашевская функция. В ней по дефолту стоит десятичная система исчесления.

2020-10-14 09:34 UTC, shapurid commented on server/routes/notFound.js
> +  app.get('/*', (req, reply) => {
Нет.
Если заменить на app.all, к сожалению, fastify-method-override будет работать некорректно. Те НЕ get и НЕ post запросы, у которых нет post аналога, будут расценены как несуществующие и будет выкидываться ошибка.

2020-10-14 09:36 UTC, shapurid commented on server/routes/session.js
> +          throw new SchemaError(validationError);
Можно. Но тогда во всех роутах, где нет валидации данных через схему, придется ставить attachValidation: true.