add tasks, add tests, add locales
shapurid/backend-project-lvl4 pull request #12
Opened 2020-10-21 14:55 UTC by shapurid

2020-10-21 19:49 UTC, foofaev requested changes

2020-10-21 19:49 UTC, foofaev commented on server/migrations/20201016151627_tasks.js
> +  table.foreign('executor_id').references('id').inTable('users');
не суть важно, но можно указывать прямо при создании колонки, что она референится
table.integer(name).references('id).inTable...

2020-10-21 19:49 UTC, foofaev commented on server/routes/session.js
>          throw new Error(error);
Поймать ошибку и без обработки ее кинуть?
Для чего? Это хак для обхода чего-то?

2020-10-21 19:49 UTC, foofaev commented on server/routes/tasks.js
> +        console.log(error);
Все еще не понимаю, зачем это может быть нужно

2020-10-21 19:49 UTC, foofaev commented on server/routes/tasks.js
> +        const data = assign(normalizedBody, { creatorId: req.currentUser.id });
assign мутирует объект
почему нельзя использовать обычный spread?

2020-10-21 19:49 UTC, foofaev commented on server/locales/ru.js
> +          info: 'До свидания. Ждем Вас снова!',
Тут и ниже. Хорошо бы по аналогии с остальным делать
Выше в коде success / error. А тут info. Хотя по логике это success. Если надо будет добавить плашку об ошибке удаление, то будет info / error?

2020-10-22 12:18 UTC, shapurid commented on server/routes/session.js
>          throw new Error(error);
Это сделано для того, что бы введенный пользователем email не удалялся в случае ошибки.

2020-10-22 12:19 UTC, shapurid commented on server/routes/tasks.js
> +        console.log(error);
Забыл убрать отладочную печать в консоль.

2020-10-22 12:32 UTC, shapurid commented on server/routes/tasks.js
> +        const data = assign(normalizedBody, { creatorId: req.currentUser.id });
Можно. Немного увлекся лодашем.

2020-10-22 12:37 UTC, shapurid commented on server/locales/ru.js
> +          info: 'До свидания. Ждем Вас снова!',
Согласен, как-то не очень логично выходит.

2020-10-22 13:43 UTC, shapurid commented on server/migrations/20201016151627_tasks.js
> +  table.foreign('executor_id').references('id').inTable('users');
Забыл поправить. Спасибо!

2020-10-22 19:54 UTC, foofaev requested changes

2020-10-22 19:54 UTC, foofaev commented on server/lib/normalizeBodyForTask.js
> +  const emptyStringsToNulls = mapValues(body, (el) => (el.length > 0 ? el : null));
el || null выглядело бы лучше

2020-10-22 19:54 UTC, foofaev commented on server/routes/tasks.js
> +        const bodyWithoutMethod = omit(req.body, '_method');
Хорошо знать методы лодаша. Но нужно помнить, сколько лодашу лет. Если можно что-то сделать просто и нативно, то лучше это делать нативно.
const {_method, ...body} = req.body;

2020-10-22 19:54 UTC, foofaev commented on server/lib/normalizeBodyForTask.js
> +  const emptyStringsToNulls = mapValues(body, (el) => (el.length > 0 ? el : null));
В целом меня очень смущает эта функция.
У нас в сущности 4-5 полей. Из них к number | null надо привести три.
И заводить под это отдельную функцию выглядит как overingeneering
Иногда KISS > DRY

2020-10-22 19:56 UTC, foofaev requested changes

2020-10-22 19:56 UTC, foofaev commented on __tests__/app.test.js
> +  const creationRes = await request(app.server)
Логин и получение сессионной куки повторяется из раза в раз. Такой код можно смело выделить в отдельную функцию и убрать в тестхелперы

2020-10-22 20:02 UTC, shapurid commented on server/routes/tasks.js
> +        const bodyWithoutMethod = omit(req.body, '_method');
Линтер начинает ругаться на неиспользуемую переменную.

2020-10-23 12:56 UTC, shapurid commented on __tests__/app.test.js
> +  const creationRes = await request(app.server)
Я тут подумал, а может просто вынести сессионную куку в глобальную переменную и использовать её в других тестах?

2020-10-23 20:13 UTC, foofaev approved these changes

2020-10-24 15:15 UTC, merged